[package]
name = "baremetal"
version = "0.0.1"
authors = ["a.pillos"]
edition = "2018"

[dependencies]
num-bigint = "0.2.6"
num-traits = "0.2.11"
actix-web = "2.0.0"
actix-rt = "1.1.0"
tramp = "0.3.0"
uuid = { version = "0.8", features = ["serde", "v4"] }